 #!/usr/bin/env bash

g++ -Wall -O CODE_TOOL_Script_to_CodeFileGenerator.cpp -o EXE_TOOL_Script_to_CodeFileGenerator

./EXE_TOOL_Script_to_CodeFileGenerator ./KinAdvLab/Kinetic_Advective_Full_CN_XOKA_Comparison/MASTER_CODE_CN2D_ChiCalculator.cpp ./KinAdvLab/Kinetic_Advective_Full_CN_XOKA_Comparison/CODE_codeFileGenerator_CN2D_ChiCalculator.cpp

./EXE_TOOL_Script_to_CodeFileGenerator ./KinAdvLab/Kinetic_Advective_Full_CN_XOKA_Comparison/MASTER_CODE_simulator_2D_CN_tINDEP.cpp ./KinAdvLab/Kinetic_Advective_Full_CN_XOKA_Comparison/CODE_codeFileGenerator_2D_CN_tINDEP.cpp

./EXE_TOOL_Script_to_CodeFileGenerator ./KinAdvLab/Kinetic_Advective_Full_CN_XOKA_Comparison/MASTER_CODE_simulator_2D_XO_KINADV_BornHuang_tINDEP.cpp ./KinAdvLab/Kinetic_Advective_Full_CN_XOKA_Comparison/CODE_codeFileGenerator_2D_XO_KINADV_BornHuang_tINDEP.cpp

./EXE_TOOL_Script_to_CodeFileGenerator ./KinAdvLab/Kinetic_Advective_Full_CN_XOKA_Comparison/MASTER_CODE_Simulator_CN_Conditional_WFs_with_XO_Trajectories.cpp ./KinAdvLab/Kinetic_Advective_Full_CN_XOKA_Comparison/CODE_codeFileGenerator_CN_Conditional_WFs_with_XO_Trajectories.cpp
